const NewArrivalproduct = [
  {
    "Id": 1,
    "IMG": "../src/Images/NewArrival1.jpg",
    "Brand": "Adidas",
    "Name": "Blue Shirt",
    "StarRating": 3.5,
    "Price": "$85",
    "Product_Des": "Stay stylish and comfortable with this vibrant blue shirt from Adidas. Made from premium cotton fabric, this shirt offers a perfect blend of style and comfort. Whether you're heading to work or hanging out with friends, this shirt is sure to make a statement.",
    "Main_Img": "../src/Images/NewArrival1.jpg",
    "Small_img1": "../src/Images/NewArrival2.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Womens_wear"
  },
  {
    "Id": 2,
    "IMG": "../src/Images/NewArrival2.jpg",
    "Brand": "Nike",
    "Name": "Greyish Shirts",
    "StarRating": 4.2,
    "Price": "$70",
    "Product_Des": "Get that casual yet chic look with these greyish shirts from Nike. Crafted from soft and breathable fabric, these shirts are perfect for everyday wear. The classic grey color makes them versatile enough to pair with any bottom wear. Elevate your style game with these wardrobe essentials.",
    "Main_Img": "../src/Images/NewArrival2.jpg",
    "Small_img1": "../src/Images/NewArrival1.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Womens_wear"
  },
  {
    "Id": 3,
    "IMG": "../src/Images/NewArrival3.jpg",
    "Brand": "Puma",
    "Name": "Off White shirt",
    "StarRating": 4.0,
    "Price": "$88",
    "Product_Des": "Elevate your formal attire with this elegant off-white shirt from Puma. Made from high-quality cotton blend, this shirt features a classic design with a modern twist. Whether you're attending a business meeting or a dinner date, this shirt is sure to leave a lasting impression.",
    "Main_Img": "../src/Images/NewArrival3.jpg",
    "Small_img1": "../src/Images/NewArrival2.jpg",
    "Small_img2": "../src/Images/NewArrival1.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Womens_wear"
  },
  {
    "Id": 4,
    "IMG": "../src/Images/NewArrival4.jpg",
    "Brand": "Reebok",
    "Name": "Half sleves Shirt",
    "StarRating": 4.5,
    "Price": "$65",
    "Product_Des": "Classic and comfortable, this half sleeves shirt from Reebok is a wardrobe essential. Made from soft and breathable fabric, this shirt offers all-day comfort. The versatile design makes it suitable for both casual and semi-formal occasions. Add this timeless piece to your collection today.",
    "Main_Img": "../src/Images/NewArrival4.jpg",
    "Small_img1": "../src/Images/NewArrival2.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival1.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Mens_wear"
  },
  {
    "Id": 5,
    "IMG": "../src/Images/NewArrival5.jpg",
    "Brand": "Under Armour",
    "Name": "Blue Denim Shirt",
    "StarRating": 4.0,
    "Price": "$82",
    "Product_Des": "Make a style statement with this trendy blue denim shirt from Under Armour. Crafted from premium quality denim fabric, this shirt offers durability and style. Whether you're heading to a casual outing or a weekend getaway, this shirt is sure to keep you looking stylish.",
    "Main_Img": "../src/Images/NewArrival5.jpg",
    "Small_img1": "../src/Images/NewArrival2.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Mens_wear"
  },
  {
    "Id": 6,
    "IMG": "../src/Images/NewArrival6.jpg",
    "Brand": "Fila",
    "Name": "Casual Brown Shirt",
    "StarRating": 4.2,
    "Price": "$76",
    "Product_Des": "Relax in style with this casual brown shirt from Fila, perfect for any occasion. Made from lightweight and breathable fabric, this shirt offers superior comfort. Whether you're lounging at home or running errands, this shirt is a must-have for your wardrobe.",
    "Main_Img": "../src/Images/NewArrival6.jpg",
    "Small_img1": "../src/Images/NewArrival2.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Mens_wear"
  },
  {
    "Id": 7,
    "IMG": "../src/Images/NewArrival7.jpg",
    "Brand": "Sketchers",
    "Name": "Shorts",
    "StarRating": 3.8,
    "Price": "$83",
    "Product_Des": "Stay cool and comfortable with these versatile shorts from Sketchers. Made from quick-drying fabric, these shorts are perfect for your active lifestyle. Whether you're hitting the gym or going for a leisurely stroll, these shorts will keep you comfortable all day long.",
    "Main_Img": "../src/Images/NewArrival7.jpg",
    "Small_img1": "../src/Images/NewArrival6.jpg",
    "Small_img2": "../src/Images/NewArrival3.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Mens_wear"
  },
  {
    "Id": 8,
    "IMG": "../src/Images/NewArrival8.jpg",
    "Brand": "Converse",
    "Name": "Trending Astronaut T-Shirts",
    "StarRating": 4.7,
    "Price": "$88",
    "Product_Des": "Stand out from the crowd with these unique astronaut-themed t-shirts from Converse. Made from high-quality cotton fabric, these t-shirts offer both style and comfort. Whether you're a space enthusiast or just love unique fashion, these t-shirts are sure to turn heads wherever you go.",
    "Main_Img": "../src/Images/NewArrival8.jpg",
    "Small_img1": "../src/Images/NewArrival6.jpg",
    "Small_img2": "../src/Images/NewArrival7.jpg",
    "Small_img3": "../src/Images/NewArrival4.jpg",
    "Small_img4": "../src/Images/NewArrival5.jpg",
    "Stock": 20,
    "Category": "Mens_wear"
  }
];


export default NewArrivalproduct;

